#!/usr/bin/env bash
# Script to install nginx web server

apt-get -y update
apt-get -y install nginx
sed -i '21s/^listen .*/listen 80' /etc/nginx/sites-enabled/default
echo "Hello World!" > /var/www/html/index.html
service nginx start
