#!/usr/bin/env bash
# Configure the server to return 404 Not found

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
sudo touch /var/www/html/error-page.html
echo "Ceci n\'est pas une page" > /var/www/html/error-page.html
printf %s "server {
        listen 80;
        listen [::]:80 default_server;
        root /var/www/html;
        index index.html index.htm;

        location /redirect_me {
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}
	
	error_page 404 /error-page.html;
        location = /error-page.html {
                root /var/www/html;
                internal;
        }
}" > /etc/nginx/sites-available/default

sudo service nginx reload
