#!/usr/bin/env bash
# A custom Nginx response header

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello world!" > /var/www/html/index.html
sudo touch /var/www/html/error-page.html
echo "Ceci n\'est pas une page" > /var/www/html/error-page.html
printf %s "server {
	listen 80;
        listen [::]:80 default_server;
        root /var/www/html;
        index index.html index.htm;
        server_name _;
        location / {
                add_header X-Served-By $HOSTNAME;
                try_files $uri $uri/ =404;
        }

	location /redirect_me { 
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}
	error_page 404 /error-page.html;
	location = /error-page.html {
		root /var/www/html;
		internal
	}
}" > /etc/nginx/sites-available/default

sudo service nginx reload
