#!/usr/bin/env bash
# Script to install HAproxy load balancer

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt install -y haproxy

printf %s "global
    log         127.0.0.1 local2 
    chroot      /var/lib/haproxy
    pidfile     /var/run/haproxy.pid
    maxconn     4000
    user        haproxy
    group       haproxy
    daemon

defaults
    mode                    http
    log                     global
    option                  httplog
    option                  dontlognull
    option http-server-close
    option forwardfor       except 127.0.0.0/8
    option                  redispatch
    retries                 3
    timeout http-request    10s
    timeout queue           1m
    timeout connect         10s
    timeout client          1m
    timeout server          1m
    timeout http-keep-alive 10s
    timeout check           10s
    maxconn                 3000

listen haproxy3-monitoring *:80
    mode http
    option forwardfor
    option httpclose
    stats enable
    stats show-legends
    stats refresh 5s
    stats uri /stats
    stats realm Haproxy\ Statistics
    stats auth howtoforge:howtoforge
    stats admin if TRUE
    default_backend app-main

frontend main
    bind *:80
    option http-server-close
    option forwardfor
    default_backend app-main

backend app-main
    balance roundrobin                
    option httpchk HEAD / HTTP/1.1\r\nHost:\ localhost
    server 904-web-01 35.196.211.2:80 check
    server 904-web-02 3.236.105.194:80 check
" > /etc/haproxy/haproxy.cfg
